db_name: "feeddy"

bot_url: "https://t.me/rss_feeddy_bot"

reader_timeout: 5

messages:
  responses:
    start: "Я сохранил тебя в системе. Теперь ты можешь присылать мне ссылки на фиды"
    already_authorized: "Ты уже авторизован. Присылай ссылку, а я ее сохраню."
    saved_successfully: "Ссылка успешно сохранена!"
    removed_successfully: "Ссылка успешно удалена!"
    list_empty: "Список ссылок пуст!"
    unknown_command: "Я не знаю такой команды"
    help: |
      Доступные команды:
      /start - авторизация, сохранение своего пользователя в системе
      /list - список сохраненных ссылок
      /remove <link> - удалить конкретную ссылку

      Ввод простого текста (не комманд) воспринимается системой как "добавление ссылки", поэтому будет произведена соответствующая валидация введенного текста
  errors:
    invalid_url: "Это невалидная ссылка"
    unauthorized: "Ты не авторизован! Используй команду /start"
    unable_to_save: "Увы, не удалось сохранить ссылку. Попробуй еще раз позже"
    default: "Произошла неизвестная ошибка"
